<a href="https://colab.research.google.com/github/KoheiSakatani/selfPR/blob/master/%E3%82%B9%E3%82%AF%E3%83%AC%E3%82%A4%E3%83%94%E3%83%B3%E3%82%B0%E3%81%AE%E3%82%84%E3%81%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
import os

os.chdir('My Drive')
os.listdir()

['実行委員長挨拶.docx',
 'H29年度健康診断.pdf',
 '1530853767388.png',
 'Colab Notebooks',
 'test_image']

In [0]:
import requests
from bs4 import BeautifulSoup

response = requests.get('http://yahoo.jp')
soup = BeautifulSoup(response.text,'lxml')
title = soup.title.string
print(title)

Yahoo! JAPAN


In [0]:
import requests
from bs4 import BeautifulSoup

response = requests.get('http://yahoo.jp')
soup = BeautifulSoup(response.text,'lxml')
link = soup.a.get('href')
print(link)

https://www.yahoo-help.jp/


In [0]:
import requests
import re
from bs4 import BeautifulSoup

url = "https://search.nifty.com/imagesearch/search?cflg=%E6%A4%9C%E7%B4%A2&select=1&chartype=&q=%E7%8C%AB&xargs=&img.fmt=all&img.imtype=color&img.filteradult=no&img.type=all&img.dimensions=all&start=%s&num=20"
keyword = "猫"
r = requests.get(url%(keyword))
soup = BeautifulSoup(r.text,'lxml')
imgs = soup.find_all('img',src=re.compile('^https://msp.c.yimg.jp/yjimage'))
for img in imgs:
        print(img['src'])

https://msp.c.yimg.jp/yjimage?q=mAWpfREXyLFaXpneMOzosIim16x7Q309f27ZoMJIPRCXJ.x5dQgNn2gBh38KgEH6ex2sbHpGZpCIqPPGOFnMC7xu9ia.lE0E6.HsTOOz7nKJa4y3wc3MkRDwqCF8_fXQhRa22BnWCntFS2PLQ9TGIqCH7CE-&sig=13f82umh7&x=77&y=116
https://msp.c.yimg.jp/yjimage?q=uM8C_TEXyLE.Cc9tNRmYt7o8xdSXziqYWxNscUBCVSemtIZUIZ4Ovu1u.vBxU7sP45CuMk7XBUjiOn4reIKqkEPCXwasS0KqGkIXjMZEdXyT3i3.nLpeKHMWwjwm4yi2bdP5OjTorguF_UiHcvfJr6._6lok&sig=13giln94b&x=137&y=86
https://msp.c.yimg.jp/yjimage?q=SwxfIgwXyLHXeYdDSZIiCaB4g3nD.INZyK4h70WIeY88R11c33ig7JBwt6UXndacjdbw.qnFeKbMa7xlTIqrxyG1oN.m9EopgIiEzzh79yOZogOEetiTI3St9gTU1CdUV6l_Cl3dKFEdamFyHHH7QA30_kfTmYk-&sig=13i6ivepu&x=143&y=143
https://msp.c.yimg.jp/yjimage?q=kAX1fjMXyLEiSXFIlzi0wj6BNNwXJvVnnQ1MFPzyRkEoFiO.B_lDLyFW9qRpf0wu.p1sKaeo9KuuAlkZWJG6OlsvvIF6R8_7fCInjh4PeFq_sD6rrm6n9lKIqf_vQJuCgZAgkg6ICHGe1wvo049njyStap8-&sig=13ftfdp17&x=137&y=103
https://msp.c.yimg.jp/yjimage?q=IzACJgoXyLG70dRms.OeU0_PF4qfsOsu_PGBSH2kA2gXV54BX.nL0sJzVtm00ZvDES3.fao3FyVFSvZs0q6S1pk7.rbq0HDc1UBfraVMOU

In [0]:
import os
os.getcwd()
os.listdir()
#os.chdir('/sample_data')


['anscombe.json',
 'README.md',
 'california_housing_test.csv',
 'california_housing_train.csv',
 'mnist_train_small.csv',
 'mnist_test.csv']

In [0]:
import os

os.getcwd()


In [0]:
import requests
import re
import uuid
from bs4 import BeautifulSoup

#url = "https://search.nifty.com/imagesearch/search?select=1&q=%s&ss=up"
url = "https://search.nifty.com/imagesearch/search?select=1&q=%s&ss=up"
keyword = "柴犬"

r = requests.get(url%(keyword))
soup = BeautifulSoup(r.text,'lxml')
imgs = soup.find_all('img',src=re.compile('^https://msp.c.yimg.jp/yjimage'))
for img in imgs:
        print(img['src'])
        r = requests.get(img['src'])
        with open(str('/content/gdrive/My Drive/test_image_shiba/')+str(uuid.uuid4())+str('.jpeg'),'wb') as file:
                file.write(r.content)

https://msp.c.yimg.jp/yjimage?q=6cQqnEIXyLEsUpwun4CoG83ooo.J1TNpvvShixn7EFQnjRUBU3akkPApSM2R9XP7C3I0xqnDraqvQN1BKN9YcGUrtcAY5K2mG0YeszB90Kt85NLNtW79bmT816ONF0dMSGz1nm55MC0LbnLIyIYbFyvDLVM-&sig=13fncibqi&x=124&y=87
https://msp.c.yimg.jp/yjimage?q=hU.nCiwXyLG1cq.qDRGCTIRxa1w30QxwsNQlr1uODjv8tzOl9B2jfiywhRumyk4qP3mrSVO.oPU1PlVLgczSJEN2yDtLdQQ6DHOrb4rSB5CSfvtRn5I3MlcPKEQ2jMUBwBusAWYAjM6XaD3oxq27F7wgzp_D&sig=13gccd8jv&x=142&y=95
https://msp.c.yimg.jp/yjimage?q=UT6IQwkXyLFCLJxCOtpCTRO9OEWttCWOvnnuOZH6hk4pI7s4R5_e5iXzpFhznw83vl7V6sFNPfrvrm1ZuUX2BzixY9vLKkfXRwbaknXmmse8FFELE0lvvo.uOwWGBB9PaMTxGLJVCrnuHLv4KLh2zGiIDnk-&sig=13fj94b7r&x=140&y=78
https://msp.c.yimg.jp/yjimage?q=9HrDO.8XyLFCrMqR4y5_Z2yFuvZm7PZ0fbTfpfm6kecn3pQ3US9JFX1pcXBt9KDiK2pgTh7eW.jAszFLsa5j6PkVaMB4anA.SoSY_CuZrGAJ3TTzUl205XqG14Gjk9CZMaJZekb0Ohgfjx.MFjONUCVVF.Ex&sig=13ge71v7k&x=141&y=94
https://msp.c.yimg.jp/yjimage?q=1eCE5jcXyLEB5mish_FugKffeDJJZvOsv8tU4afAF.wTsYtsNZE443G0UXoxiIWl44BM1zEtQl6a9.xNRX2x2eXEY7Il2QY8wrsxVsb4D0Cs9vJ3

In [0]:
import requests
import re
import uuid
from bs4 import BeautifulSoup
#url = "https://search.nifty.com/imagesearch/search?select=1&chartype=&q=%s&xargs=2&img.fmt=all&img.imtype=color&img.filteradult=no&img.type=all&img.dimensions=large&start=%s&num=20" #多分猫
#url = "https://search.nifty.com/imagesearch/search?select=1&chartype=&q=%s&xargs=&img.fmt=all&img.imtype=color&img.filteradult=no&img.type=all&img.dimensions=all&start=%s&num=20"#柴犬
#url = "https://search.nifty.com/imagesearch/search?select=1&chartype=&q=%s&xargs=&img.fmt=all&img.imtype=color&img.filteradult=no&img.type=all&img.dimensions=all&start=%s&num=20" #土佐犬
#url = "https://search.nifty.com/imagesearch/search?&select=1&chartype=&q=%s&xargs=&img.fmt=all&img.imtype=color&img.filteradult=no&img.type=all&img.dimensions=all&start=%s&num=20"#北海道犬
url = "https://search.nifty.com/imagesearch/search?&select=1&chartype=&q=%s&xargs=2&img.fmt=all&img.imtype=color&img.filteradult=no&img.type=all&img.dimensions=all&start=%s&num=20"#紀州犬
keyword = "紀州犬"
pages = [400,420,440,460,480,500,520,540,560,580]

for p in pages:
        r = requests.get(url%(keyword,p))
        soup = BeautifulSoup(r.text,'lxml')
        imgs = soup.find_all('img',src=re.compile('^https://msp.c.yimg.jp/yjimage'))
        for img in imgs:
                print(img['src'])
                r = requests.get(img['src'])
                with open(str('/content/gdrive/My Drive/test_image/test_image_kisyu/')+str(uuid.uuid4())+str('.jpeg'),'wb') as file:
                        file.write(r.content)

https://msp.c.yimg.jp/yjimage?q=9zGLGl8XyLFGhX83mftkMPaP8grPYEzzwaBUzbRXxsPH2foRiP6FQndDrK.Rm3sz25MGxEmDAahT5I1DZMIr._W9HLwqoxWWZBcys.o1afB0J3Tmps9YGM3mpCtNMh5vlPTcfE6cE.x66abvnHVRo4qwnAg-&sig=13fduil9h&x=135&y=101
https://msp.c.yimg.jp/yjimage?q=2jNNGxsXyLGx_nQJq5kEysonMd6Ibhs4Snrv2At97lJZL1g3m4atHImAkoNWkM5tslvJ7QnE.tV1ZTzfWZz.q8rsf3Sdlt89OJeGyWJm0wvoI7CKvJrpMBk7U.uKndKmIZeVyjF9Q3BLU1Ef.FmxV8sScfY-&sig=13f3plnfp&x=137&y=103
https://msp.c.yimg.jp/yjimage?q=bJJEGVsXyLF.euJsRaqQz5vh0b89d4P1HCYps2ByDT5TXhFaLH6roDQG7gpPjM8JGH40PCPNUiWWqSbfyjDBeynL4cfZjRCVlHkACsPpOaEI3uNpqLgLeEHbSt_mo6ygRp5cctlnY6Km5hMHX5Pq_oRjhQ--&sig=13eg4ap01&x=77&y=116
https://msp.c.yimg.jp/yjimage?q=f.lfXlsXyLGd2T.HdPPeM6Jq0n6ST.FNpN_wHsVdeG7XBqxs8K3yjOn7vDU8VRWiC.QfmkzaMYrRenqQU8jetV_2q_euvLU745IjxNJQNSq1livCslWIDkbP2m25EEZerg3wl_cS9.aV8ErSKePgku7taV0-&sig=13f1m2fj3&x=111&y=134
https://msp.c.yimg.jp/yjimage?q=kswOMOMXyLHPM6LBS9WpH0NW9DUdPTkHVPLOrjLWU9eApPkiflH8oejkCr4yGq7Bd.1PJCAMK9ZC92ot9vi.ea32WIk8_znAWZ6XQgewOw.VL

In [0]:
import os

os.getcwd()
os.listdir()

['実行委員長挨拶.docx',
 'H29年度健康診断.pdf',
 'Colab Notebooks',
 'test_image_cat',
 'test_image_shiba',
 'test_image_tosa',
 'test_image_hokkai',
 'test_image_kisyu']

In [0]:
#https://newtechnologylifestyle.net/keras%E3%81%AEcnn%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%A6%E3%82%AA%E3%83%AA%E3%82%B8%E3%83%8A%E3%83%AB%E7%94%BB%E5%83%8F%E3%81%A7%E7%94%BB%E5%83%8F%E8%AA%8D%E8%AD%98%E3%82%92%E8%A1%8C%E3%81%A3/
#を大きく参照

#google Colaboratryでのファイル操作はgdriveを/contentにマウントする必要あり
#これはhttps://qiita.com/uni-3/items/201aaa2708260cc790b8 ,  http://www.bokupy.com/detail/53を参照

import keras
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers.convolutional import Conv2D, MaxPooling2D
from keras.layers.core import Dense, Dropout, Activation, Flatten
import numpy as np
from sklearn.model_selection import train_test_split
from PIL import Image
import glob

#分類するフォルダの名前を格納
folder = ["test_image_shiba","test_image_tosa","test_image_hokkai","test_image_kisyu"]

#50×50にリサイズ→画像によっては引き伸ばしになるため、16×16に変更してみる
image_size = 50

#画像データ,正解ラベルの配列
X = []
Y = []

#画像と正解ラベルの格納
for index, name in enumerate(folder):
  dir = '/content/gdrive/My Drive/test_image/' + name
  files = glob.glob(dir + "/*.jpeg") #拡張子に気を付けて
  for i, file in enumerate(files):
        image = Image.open(file) #フォルダを開く
        image = image.convert("RGB") #RGB値を変換
        image = image.resize((image_size, image_size)) #画像のリサイズ
        data = np.asarray(image) #画像をデータに変換(日本語がおかしいけど伝わるやろ)
        X.append(data)
        Y.append(index)

#扱いやすいようにnumpyに変換
X = np.array(X)
Y = np.array(Y)
print("X")
print(X)
print("X.shape")
print(X.shape)
#3次元を4次元に
#X = np.expand_dims(X, axis=0)

#データの正規化
X = X.astype('float32')
X = X / 255.0 #RGB値は0〜255なので255で割る

# 正解ラベルの形式を変換
Y = np_utils.to_categorical(Y, 4)

# 学習用データとテストデータ
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, shuffle = True)

print("X_train.shape")
print(X_train.shape)

# CNNを構築
model = Sequential()
 
model.add(Conv2D(32, (3, 3), padding='same',input_shape=X_train.shape[1:]))
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

#model.add(Conv2D(128, (3, 3), padding='same'))
#model.add(Activation('relu'))
#model.add(Conv2D(128, (3, 3)))
#model.add(Activation('relu'))
#model.add(MaxPooling2D(pool_size=(2, 2)))
#model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(4))
model.add(Activation('softmax'))
#転移学習を実施(最初の2層を固定)
for layer in model.layers[:2]:
  layer.trainable = False

#モデルの表示
model.summary()

# コンパイル
model.compile(loss='categorical_crossentropy',optimizer='SGD',metrics=['accuracy'])

#訓練
history = model.fit(X_train, y_train, epochs=400)

#評価 & 評価結果出力
print(model.evaluate(X_test, y_test))

X
[[[[224 224 216]
   [218 218 210]
   [189 186 177]
   ...
   [207 207 199]
   [212 212 204]
   [214 214 206]]

  [[219 218 213]
   [214 214 206]
   [201 198 189]
   ...
   [214 214 206]
   [220 220 212]
   [224 224 216]]

  [[215 214 209]
   [213 212 207]
   [207 204 197]
   ...
   [214 214 206]
   [222 222 214]
   [225 225 217]]

  ...

  [[122 110  96]
   [144 132 116]
   [138 111  84]
   ...
   [173 169 160]
   [162 158 149]
   [154 150 141]]

  [[ 91  83  70]
   [152 142 130]
   [157 131 104]
   ...
   [198 194 185]
   [198 194 185]
   [182 178 169]]

  [[133 129 118]
   [146 140 128]
   [136 112  86]
   ...
   [198 194 185]
   [199 195 186]
   [187 183 174]]]


 [[[245 244 242]
   [246 245 243]
   [247 246 244]
   ...
   [242 240 241]
   [240 238 239]
   [239 237 238]]

  [[245 244 242]
   [246 245 243]
   [247 246 244]
   ...
   [242 240 241]
   [241 239 240]
   [240 238 239]]

  [[245 244 242]
   [246 245 243]
   [247 246 244]
   ...
   [242 240 241]
   [242 240 241]
   [241 2